buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    if (project.name != "app") {
        project.ext.set("flutter", [
            compileSdkVersion: 34,
            targetSdkVersion: 34,
            minSdkVersion: 21,
            buildToolsVersion: "34.0.0"
        ])
    }
}

subprojects {
    if (project.name != "app") {
        if (project.state.executed) {
            if (project.hasProperty("android")) {
                project.android {
                    if (namespace == null || namespace.isEmpty()) {
                        namespace = (project.group && !project.group.isEmpty()) ? project.group : "ca.crbcl.${project.name.replace('-', '_')}"
                    }
                    compileSdkVersion 34
                    buildToolsVersion "34.0.0"
                }
            }
        } else {
            project.afterEvaluate { p ->
                if (p.hasProperty("android")) {
                    p.android {
                        if (namespace == null || namespace.isEmpty()) {
                            namespace = (p.group && !p.group.isEmpty()) ? p.group : "ca.crbcl.${p.name.replace('-', '_')}"
                        }
                        compileSdkVersion 34
                        buildToolsVersion "34.0.0"
                    }
                }
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
