"""Permission constants for CRBCL Platform."""

from enum import StrEnum


class Permissions(StrEnum):
    # Intake & Referral permissions (Phase 3)
    INTAKE_READ = "intake.read"
    INTAKE_CREATE = "intake.create"
    INTAKE_UPDATE = "intake.update"
    INTAKE_DELETE = "intake.delete"
    INTAKE_ASSIGN = "intake.assign"
    INTAKE_SUBMIT = "intake.submit"
    INTAKE_APPROVE = "intake.approve"
    INTAKE_RETURN = "intake.return"
    INTAKE_REPORTER_READ = "intake.reporter.read"
    INTAKE_REPORTER_WRITE = "intake.reporter.write"
    INTAKE_DECISION_READ = "intake.decision.read"
    INTAKE_DECISION_WRITE = "intake.decision.write"
    INTAKE_HISTORY_READ = "intake.history.read"
    INTAKE_LINK_READ = "intake.link.read"
    INTAKE_LINK_WRITE = "intake.link.write"

    # Client permissions
    CLIENT_READ = "client.read"
    CLIENT_CREATE = "client.create"
    CLIENT_UPDATE = "client.update"
    CLIENT_DELETE = "client.delete"

    # Field-level client permissions
    CLIENT_IDENTIFIERS_READ = "client.identifiers.read"
    CLIENT_IDENTIFIERS_WRITE = "client.identifiers.write"
    CLIENT_MEDICAL_READ = "client.medical.read"
    CLIENT_MEDICAL_WRITE = "client.medical.write"
    CLIENT_SCHOOL_READ = "client.school.read"
    CLIENT_SCHOOL_WRITE = "client.school.write"
    CLIENT_CULTURAL_READ = "client.cultural.read"
    CLIENT_CULTURAL_WRITE = "client.cultural.write"
    CLIENT_DOCUMENTS_READ = "client.documents.read"
    CLIENT_DOCUMENTS_WRITE = "client.documents.write"

    # Family permissions
    FAMILY_READ = "family.read"
    FAMILY_CREATE = "family.create"
    FAMILY_UPDATE = "family.update"
    FAMILY_DELETE = "family.delete"
    FAMILY_RELATIONSHIPS_READ = "family.relationships.read"
    FAMILY_RELATIONSHIPS_WRITE = "family.relationships.write"

    # Household permissions
    HOUSEHOLD_READ = "household.read"
    HOUSEHOLD_WRITE = "household.write"

    # Provider permissions
    PROVIDER_READ = "provider.read"
    PROVIDER_WRITE = "provider.write"

    # School permissions
    SCHOOL_READ = "school.read"
    SCHOOL_WRITE = "school.write"

    # Core Case permissions (Phase 4)
    CASE_READ = "case.read"
    CASE_CREATE = "case.create"
    CASE_UPDATE = "case.update"
    CASE_DELETE = "case.delete"
    CASE_ASSIGN = "case.assign"
    CASE_CLOSE = "case.close"
    CASE_REOPEN = "case.reopen"

    # Case Sub-domain permissions (Phase 4)
    CASE_PEOPLE_READ = "case.people.read"
    CASE_PEOPLE_WRITE = "case.people.write"
    CASE_ASSIGNMENT_READ = "case.assignment.read"
    CASE_ASSIGNMENT_WRITE = "case.assignment.write"
    CASE_EXTERNAL_WORKER_READ = "case.external_worker.read"
    CASE_EXTERNAL_WORKER_WRITE = "case.external_worker.write"
    CASE_SOURCE_READ = "case.source.read"
    CASE_SOURCE_WRITE = "case.source.write"
    CASE_LINK_READ = "case.link.read"
    CASE_LINK_WRITE = "case.link.write"
    CASE_RESTRICTION_READ = "case.restriction.read"
    CASE_RESTRICTION_MANAGE = "case.restriction.manage"
    CASE_TRANSFER_READ = "case.transfer.read"
    CASE_TRANSFER_CREATE = "case.transfer.create"
    CASE_TRANSFER_APPROVE = "case.transfer.approve"

    # Case note permissions (Phase 4)
    CASE_NOTE_READ = "case_note.read"
    CASE_NOTE_CREATE = "case_note.create"
    CASE_NOTE_UPDATE = "case_note.update"
    CASE_NOTE_COMPLETE = "case_note.complete"
    CASE_NOTE_LOCK = "case_note.lock"
    CASE_NOTE_UNLOCK = "case_note.unlock"
    CASE_NOTE_ADDENDUM = "case_note.addendum"
    CASE_NOTE_EXPORT = "case_note.export"

    # Document permissions
    DOCUMENT_READ = "document.read"
    DOCUMENT_UPLOAD = "document.upload"
    DOCUMENT_DELETE = "document.delete"

    # Assessment Engine permissions (Phase 5)
    ASSESSMENT_READ = "assessment.read"
    ASSESSMENT_CREATE = "assessment.create"
    ASSESSMENT_UPDATE = "assessment.update"
    ASSESSMENT_COMPLETE = "assessment.complete"
    ASSESSMENT_LOCK = "assessment.lock"
    ASSESSMENT_UNLOCK = "assessment.unlock"
    ASSESSMENT_REASSIGN = "assessment.reassign"
    ASSESSMENT_PRINT = "assessment.print"
    ASSESSMENT_COMPARE = "assessment.compare"
    ASSESSMENT_HOME_READ = "assessment.home.read"
    ASSESSMENT_HOME_WRITE = "assessment.home.write"
    ASSESSMENT_THREAT_READ = "assessment.threat.read"
    ASSESSMENT_THREAT_WRITE = "assessment.threat.write"
    ASSESSMENT_AIEI_READ = "assessment.aiei.read"
    ASSESSMENT_AIEI_WRITE = "assessment.aiei.write"
    ASSESSMENT_TEMPLATE_READ = "assessment.template.read"
    ASSESSMENT_TEMPLATE_MANAGE = "assessment.template.manage"

    # Plan permissions (Phase 6: Safety Plans, Case Plans, Goals, Activities, Signatures)
    PLAN_READ = "plan.read"
    PLAN_CREATE = "plan.create"
    PLAN_UPDATE = "plan.update"
    PLAN_DELETE = "plan.delete"
    PLAN_SUBMIT = "plan.submit"
    PLAN_APPROVE = "plan.approve"
    PLAN_RETURN = "plan.return"
    PLAN_FINALIZE = "plan.finalize"
    PLAN_LOCK = "plan.lock"
    PLAN_UNLOCK = "plan.unlock"
    PLAN_CLONE = "plan.clone"
    PLAN_PRINT = "plan.print"
    PLAN_SAFETY_READ = "plan.safety.read"
    PLAN_SAFETY_WRITE = "plan.safety.write"
    PLAN_CASE_READ = "plan.case.read"
    PLAN_CASE_WRITE = "plan.case.write"
    PLAN_GOAL_CREATE = "plan.goal.create"
    PLAN_GOAL_UPDATE = "plan.goal.update"
    PLAN_GOAL_COMPLETE = "plan.goal.complete"
    PLAN_ACTIVITY_CREATE = "plan.activity.create"
    PLAN_ACTIVITY_UPDATE = "plan.activity.update"
    PLAN_ACTIVITY_COMPLETE = "plan.activity.complete"
    PLAN_SIGNATURE_READ = "plan.signature.read"
    PLAN_SIGNATURE_CAPTURE = "plan.signature.capture"

    # Team & User Admin permissions
    ADMIN_USERS_MANAGE = "admin.users.manage"
    ADMIN_ROLES_MANAGE = "admin.roles.manage"
    ADMIN_TEAMS_MANAGE = "admin.teams.manage"
    ADMIN_CONFIGURATION_MANAGE = "admin.configuration.manage"

    # Audit & Timeline permissions
    AUDIT_READ = "audit.read"
    ACCESS_EVENT_READ = "access_event.read"
    TIMELINE_READ = "timeline.read"

    # Placement, Removal, Active Efforts, Permanency, Court & Background Checks (Phase 7)
    ACTIVE_EFFORTS_READ = "active_efforts.read"
    ACTIVE_EFFORTS_WRITE = "active_efforts.write"
    BACKGROUND_CHECK_READ = "background_check.read"
    BACKGROUND_CHECK_WRITE = "background_check.write"
    BACKGROUND_CHECK_ADJUDICATE = "background_check.adjudicate"
    PLACEMENT_READ = "placement.read"
    PLACEMENT_WRITE = "placement.write"
    PLACEMENT_DISCHARGE = "placement.discharge"
    REMOVAL_READ = "removal.read"
    REMOVAL_WRITE = "removal.write"
    PERMANENCY_READ = "permanency.read"
    PERMANENCY_WRITE = "permanency.write"
    VISITATION_READ = "visitation.read"
    VISITATION_WRITE = "visitation.write"
    COURT_READ = "court.read"
    COURT_WRITE = "court.write"

    # Placement Homes & Facilities (Phase 8)
    PLACEMENT_HOME_READ = "placement_home.read"
    PLACEMENT_HOME_CREATE = "placement_home.create"
    PLACEMENT_HOME_UPDATE = "placement_home.update"
    PLACEMENT_HOME_ARCHIVE = "placement_home.archive"
    PLACEMENT_HOME_MEMBER_READ = "placement_home.member.read"
    PLACEMENT_HOME_MEMBER_MANAGE = "placement_home.member.manage"
    PLACEMENT_HOME_LICENSE_READ = "placement_home.license.read"
    PLACEMENT_HOME_LICENSE_MANAGE = "placement_home.license.manage"
    PLACEMENT_HOME_BACKGROUND_CHECK_READ = "placement_home.background_check.read"
    PLACEMENT_HOME_BACKGROUND_CHECK_MANAGE = "placement_home.background_check.manage"
    PLACEMENT_HOME_ASSESSMENT_READ = "placement_home.assessment.read"
    PLACEMENT_HOME_ASSESSMENT_CREATE = "placement_home.assessment.create"
    PLACEMENT_HOME_VISIT_READ = "placement_home.visit.read"
    PLACEMENT_HOME_VISIT_CREATE = "placement_home.visit.create"
    PLACEMENT_HOME_VISIT_UPDATE = "placement_home.visit.update"
    PLACEMENT_HOME_CONTACT_READ = "placement_home.contact.read"
    PLACEMENT_HOME_CONTACT_CREATE = "placement_home.contact.create"
    PLACEMENT_HOME_DOCUMENT_READ = "placement_home.document.read"
    PLACEMENT_HOME_DOCUMENT_MANAGE = "placement_home.document.manage"
    PLACEMENT_HOME_CAPACITY_READ = "placement_home.capacity.read"
    PLACEMENT_HOME_CAPACITY_MANAGE = "placement_home.capacity.manage"
    PLACEMENT_HOME_MAP_READ = "placement_home.map.read"

    # Scheduling, Staffing & Notifications (Phase 9)
    CALENDAR_READ_OWN = "calendar.read_own"
    CALENDAR_READ_TEAM = "calendar.read_team"
    CALENDAR_WRITE = "calendar.write"
    STAFFING_READ = "staffing.read"
    STAFFING_CREATE = "staffing.create"
    STAFFING_UPDATE = "staffing.update"
    STAFFING_COMPLETE = "staffing.complete"
    NOTIFICATION_READ = "notification.read"
    NOTIFICATION_PREFERENCES_UPDATE = "notification.preferences.update"
    NOTIFICATION_TEMPLATE_READ = "notification.template.read"
    NOTIFICATION_TEMPLATE_MANAGE = "notification.template.manage"
    NOTIFICATION_DELIVERY_READ = "notification.delivery.read"
    NOTIFICATION_DELIVERY_RETRY = "notification.delivery.retry"

    # Finance, Billing, Purchase Orders, Invoices & Ledger (Phase 10)
    FINANCE_REQUEST_READ = "finance.request.read"
    FINANCE_REQUEST_CREATE = "finance.request.create"
    FINANCE_REQUEST_UPDATE = "finance.request.update"
    FINANCE_REQUEST_SUBMIT = "finance.request.submit"
    FINANCE_REQUEST_APPROVE = "finance.request.approve"
    FINANCE_REQUEST_RETURN = "finance.request.return"
    FINANCE_REQUEST_DENY = "finance.request.deny"
    FINANCE_BUDGET_READ = "finance.budget.read"
    FINANCE_BUDGET_MANAGE = "finance.budget.manage"
    FINANCE_RATE_READ = "finance.rate.read"
    FINANCE_RATE_MANAGE = "finance.rate.manage"
    FINANCE_INVOICE_READ = "finance.invoice.read"
    FINANCE_INVOICE_GENERATE = "finance.invoice.generate"
    FINANCE_INVOICE_REVIEW = "finance.invoice.review"
    FINANCE_INVOICE_FINALIZE = "finance.invoice.finalize"
    FINANCE_INVOICE_VOID = "finance.invoice.void"
    FINANCE_LEDGER_READ = "finance.ledger.read"
    FINANCE_EXPORT = "finance.export"

    # Reporting, QA, Passports, Audit Tickler & Dashboards (Phase 11)
    REPORT_READ = "report.read"
    REPORT_CREATE = "report.create"
    REPORT_SAVE = "report.save"
    REPORT_SHARE = "report.share"
    REPORT_EXPORT = "report.export"
    REPORT_CHILD_PASSPORT = "report.child_passport"
    REPORT_PARENT_PASSPORT = "report.parent_passport"
    QA_READ = "qa.read"
    QA_AUDIT_CREATE = "qa.audit.create"
    QA_AUDIT_COMPLETE = "qa.audit.complete"
    QA_TEMPLATE_MANAGE = "qa.template.manage"
    DASHBOARD_CUSTOMIZE = "dashboard.customize"
    DASHBOARD_EXECUTIVE = "dashboard.executive"

    # Fleet Management, Trips, Maintenance, Insurance, GPS & Telematics (Phase 12)
    FLEET_READ = "fleet.read"
    FLEET_VEHICLE_READ = "fleet.vehicle.read"
    FLEET_VEHICLE_CREATE = "fleet.vehicle.create"
    FLEET_VEHICLE_UPDATE = "fleet.vehicle.update"
    FLEET_VEHICLE_ARCHIVE = "fleet.vehicle.archive"
    FLEET_TRIP_READ = "fleet.trip.read"
    FLEET_TRIP_CHECKOUT = "fleet.trip.checkout"
    FLEET_TRIP_CHECKIN = "fleet.trip.checkin"
    FLEET_MAINTENANCE_READ = "fleet.maintenance.read"
    FLEET_MAINTENANCE_MANAGE = "fleet.maintenance.manage"
    FLEET_INSURANCE_READ = "fleet.insurance.read"
    FLEET_INSURANCE_MANAGE = "fleet.insurance.manage"
    FLEET_LOCATION_READ = "fleet.location.read"
    FLEET_LOCATION_HISTORY = "fleet.location.history"
    FLEET_LOCATION_CAPTURE = "fleet.location.capture"
    FLEET_TELEMATICS_MANAGE = "fleet.telematics.manage"
    FLEET_GEOFENCE_READ = "fleet.geofence.read"
    FLEET_GEOFENCE_MANAGE = "fleet.geofence.manage"

    # Enterprise Integrations, M365, OCR, Ask Red Bear AI & Communications (Phase 13)
    INTEGRATION_READ = "integration.read"
    INTEGRATION_MANAGE = "integration.manage"
    OCR_PROCESS = "ocr.process"
    OCR_CONFIRM = "ocr.confirm"
    AI_QUERY = "ai.query"
    COMMUNICATIONS_MANAGE = "communications.manage"
